// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhhVPlTWntPQaQm2IAbYlsRwiQhWV_Zkc',
    appId: '1:619705700329:web:b0b3b90eafe9d3ad618578',
    messagingSenderId: '619705700329',
    projectId: 'flutter-maps-5ab34',
    authDomain: 'flutter-maps-5ab34.firebaseapp.com',
    storageBucket: 'flutter-maps-5ab34.appspot.com',
    measurementId: 'G-QVC1FS0QF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwS2_fXtAm2SNsv32yIOSm3MPEQOGRy58',
    appId: '1:619705700329:android:3dcf602e54db0f3e618578',
    messagingSenderId: '619705700329',
    projectId: 'flutter-maps-5ab34',
    storageBucket: 'flutter-maps-5ab34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jftq38y9_JZxidknr4mvzy6958B9HD4',
    appId: '1:619705700329:ios:1247778f66709fb9618578',
    messagingSenderId: '619705700329',
    projectId: 'flutter-maps-5ab34',
    storageBucket: 'flutter-maps-5ab34.appspot.com',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jftq38y9_JZxidknr4mvzy6958B9HD4',
    appId: '1:619705700329:ios:86b22489673a98b7618578',
    messagingSenderId: '619705700329',
    projectId: 'flutter-maps-5ab34',
    storageBucket: 'flutter-maps-5ab34.appspot.com',
    iosBundleId: 'com.example.flutterMaps.RunnerTests',
  );
}
